import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

STORM_WORK_DIR = Path(os.getenv("STORM_WORK_DIR", "/tmp/hivewiki-builder/storm"))

CLUSTER_THRESHOLD = 0.85
EMBED_CONTENT_CHARS = 500

KNN_CLUSTER_K = 10
RELATED_WIKI_MIN_SIMILARITY = 0.65
RELATED_WIKI_MAX_SIMILARITY = 0.85
RELATED_WIKI_K = 5

STORM_MAX_CONV_TURN = 2
STORM_MAX_PERSPECTIVE = 2
STORM_RETRIEVER_K = 5

FILENAME_MAX_LEN = 30
FILENAME_LLM_MAX_WORKERS = 5
FILENAME_LLM_TIMEOUT = 30.0
FILENAME_LLM_TEMPERATURE = 0.3
